version: "3"
services:
  condition_classifier-uplink:
    # if something fails or the server is restarted, the container will restart
    restart: always
    container_name: condition_classifier-uplink
    image: condition_classifier-uplink
    build:
      # build the condition clasifier image from the Dockerfile in the current directory
      context: .
